version: "3.8"
services:
  postgres: 
    image: postgres:14.2-alpine
    container_name: trackdb
    ports:
    - 5432:5432
#    volumes:
#    - postgres-data:/var/lib/postgresql/data
    environment:
    - POSTGRES_PASSWORD=parool
    networks:
    - pg_net
  pgamdmin4:
    image: dpage/pgadmin4:6
    container_name: pgadmintrack
    ports:
    - 8080:80
    volumes:
    - pgadmin-data:/var/lib/pgadmin
    environment:
    - PGADMIN_DEFAULT_EMAIL=test@domain.com
    - PGADMIN_DEFAULT_PASSWORD=salajane
    networks:
    - pg_net
networks:
  pg_net:
volumes:
  pgadmin-data:
# postgres-data: