variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: "/certs"
  # Minu konteineri registri aadress AWS-s (Amazon Elastic Container Registry)
  DOCKER_REGISTRY: 796708230716.dkr.ecr.eu-north-1.amazonaws.com/track
#commit changes
stages:
  - build
  - api_test
  - deploy

api_test:
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_TLS_CERTDIR: ""
  image:
    name: docker/compose:1.29.2
    entrypoint: ["/bin/sh", "-c"]
  services:
    - docker:20.10.14-dind-alpine3.15
  only:
    - main
  before_script:
    - apk add --no-cache curl jq python3 py3-pip
    - pip install awscli
    - aws ecr get-login-password | docker login --username AWS --password-stdin ${DOCKER_REGISTRY}
  script:
    - cd ApiTests
    - docker-compose up --abort-on-container-exit --exit-code-from newman
    - docker-compose down -v
  after_script:
    - docker logout ${ITB1704_REGISTRY}
  stage: api_test
  tags:
    - itb1704


build:
  image: docker:20.10.13-alpine3.15
  services:
    - docker:20.10.13-dind-alpine3.15
  only:
    - main
  before_script:
    - apk add --no-cache curl jq python3 py3-pip
    - pip install awscli
    - aws ecr get-login-password | docker login --username AWS --password-stdin ${DOCKER_REGISTRY}
  script:
    - docker build -t ${DOCKER_REGISTRY}/back:${CI_COMMIT_SHA} ./BackEnd/
    - docker build -t ${DOCKER_REGISTRY}/front:${CI_COMMIT_SHA} ./FrontENd/
    - docker push ${DOCKER_REGISTRY}/back:${CI_COMMIT_SHA}
    - docker push ${DOCKER_REGISTRY}/front:${CI_COMMIT_SHA}
  after_script:
    - docker logout ${DOCKER_REGISTRY}
  stage: build
  artifacts:
    paths:
deploy:
  image: docker:20.10.13-alpine3.15
  when: manual
  only:
    - main
  before_script:
    # teeme kindlaks, et ssh on installitud
    - "which ssh-agent || ( apt-get update -y && apt-get install openssh-client git -y )"

    # käivitame ssh
    - eval $(ssh-agent -s)

    # loeme GitLabi muutujatest private key
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -

    # loome ssh kausta ja anname ssh kaustas lugemise, kirjutamise ja käivitamise õigused
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh

    # leiame kõik serveri public key-d ja usaldame neid runneri keskkonnas
    # serveri aadress on vaja muuta enda omaks
    - ssh-keyscan ec2-16-171-45-135.eu-north-1.compute.amazonaws.com >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts

  script:
    # loome ssh ühenduse
    # serveri aadress on vaja muuta enda omaks
    - ssh ubuntu@ec2-16-171-45-135.eu-north-1.compute.amazonaws.com "sudo CI_COMMIT_SHA=${CI_COMMIT_SHA} docker-compose  -f ~/app/docker-compose.yml up -d"
  after_script:
    - exit
  stage: deploy
